import { getServerSession } from "next-auth";
import { authOptions } from "../lib/auth/auth";

import Dashboard from "./dashboard/page"

export const metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
}

export default async function Home() {
  const session = await getServerSession(authOptions);
  console.log(session);

	return (
		<main>
			<Dashboard />
		</main>
	)
}
