import { getServerSession } from "next-auth";
import { authOptions } from "../lib/auth/auth";

import Dashboard from "./dashboard/page"
import { redirect } from "next/dist/server/api-utils";

export const metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
}

export default async function Home() {
  const session = await getServerSession(authOptions);
  console.log(session);

	if(!session) return redirect('/login')

	return (
		<main>
			<Dashboard />
		</main>
	)
}
