import SearchBar from "@/components/SearchBar"
import Button from "@/components/Button"
import Link from "next/link"

import Carousel from "@/components/Carousel"

import imagem1 from "@/public/carousel/imagem1.jpg"
import imagem2 from "@/public/carousel/imagem2.jpg"
import imagem3 from "@/public/carousel/imagem3.jpg"
import Image from "next/image"

export const metadata = {
	title: "Login",
	description: "Generated by create next app",
}

export default function Login() {
	const slides = [imagem1, imagem2, imagem3]

	return (
		<section className="text-slate-950 flex bottom-0 left-0 bg-gray-50 fixed h-screen w-screen z-20">
			<div className="flex-1 flex justify-center items-center ">
				<div className="grid min-w-[40%]">
					<h1 className="font-semibold text-4xl pb-3">Log in</h1>
					<span className="text-gray-400 pb-4">Welcome Back! Please enter your user.</span>
					<div className="pb-5">
						<div className="grid gap-2 py-4">
							<span className="text-sm font-medium">Email</span>
							<SearchBar type='email' />
						</div>
						<div className="grid gap-2">
							<span className="text-sm font-medium">Password</span>
							<SearchBar type='password' />
						</div>
					</div>
					<div className="flex justify-between pb-6 items-center">
						<div className="flex gap-1">
							<input type="checkbox"/>
							<span className="text-gray-600">Remember me</span>
						</div>
						<Link className="text-sm font-bold text-slate-950 hover:underline transition-all" href={"/signup"}>Forgot password</Link>
					</div>
					<Button><Link href={"/"}>Sign in</Link></Button>
					<span className="text-gray-400 pt-4">Don&apos;t have an account? <Link className="font-bold text-slate-950 hover:underline transition-all" href={"/signup"}>Sign up</Link></span>
				</div>
			</div>
			<div className="flex-1 relative">
				<Carousel>
					{slides.map((slide, i) => (
						<Image key={i} quality={100} src={slide} alt={i} />
					))}
				</Carousel>
				<div className="absolute left-0 bottom-0 text-center right-0 z-30 pb-[20%] ">
					<h1 className="text-slate-50 text-xl font-bold">Welcome to your new dashboard</h1>
					<span className="text-slate-200">Sign in to explore changes we&apos;ve made.</span>
				</div>
			</div>
		</section>
	)
}